ERROR_NOTIFICATION_EMAIL_ADDRESSES = []
BOT_COMMAND_PREFIX = "!"

ADMIN_USER_ID = "560570108645343234"
MAX_PRODUCTS_TRACKED_PER_USER = 2

ERROR_MESSAGES = {
  "NO_PRODUCT_FOUND": "No product found for id = {}",
  "MISSING_ARGUMENTS": "The command is missing required arguments..."
}
